CREATE TABLE IF NOT EXISTS interactions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    raiting FLOAT NOT NULL,
    time_stamp TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(user_id, event_id)
);

CREATE TABLE IF NOT EXISTS similarities(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    scope FLOAT NOT NULL,
    time_stamp TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(evetn_a, event_b)
)
